
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fygG_8Gpzh0dO9m7-VD6WtWPoAfTPHft
"""

import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

import zipfile
import os

zip_path = "/content/Student_Projects.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

os.listdir(extract_path)

!pip install tensorflow

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

train_data = datagen.flow_from_directory(
    "/content/dataset",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_directory(
    "/content/dataset",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
output = Dense(train_data.num_classes, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=20
)

base_model.trainable = True

model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_fine = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

loss, accuracy = model.evaluate(val_data)
print(f"Final Validation Accuracy: {accuracy * 100:.2f}%")

model.save("/content/plant_classification_model.h5")

import matplotlib.pyplot as plt


acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

if 'history_fine' in globals():
    acc += history_fine.history['accuracy']
    val_acc += history_fine.history['val_accuracy']

epochs = range(len(acc))

plt.figure(figsize=(8, 5))
plt.plot(epochs, acc, label='Training Accuracy')
plt.plot(epochs, val_acc, label='Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

import numpy as np
import cv2
from tensorflow.keras.preprocessing import image
import os


dataset_root = "/content/dataset"


class_dirs = [d for d in os.listdir(dataset_root) if os.path.isdir(os.path.join(dataset_root, d))]

img_path = None
if class_dirs:
    
    first_class_dir = os.path.join(dataset_root, class_dirs[0])

    
    image_files = [f for f in os.listdir(first_class_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))]

    if image_files:
        
        img_path = os.path.join(first_class_dir, image_files[0])
        print(f"Using image: {img_path} for testing.")
    else:
        print(f"No image files found in the directory: {first_class_dir}")
else:
    print(f"No class directories found in the dataset root: {dataset_root}")

if img_path:
    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0
    print("Image loaded successfully.")
else:
    print("Could not load any image for testing. Please ensure your dataset contains images.")

pred = model.predict(img_array)
class_index = np.argmax(pred)
confidence = np.max(pred) * 100

class_names = list(train_data.class_indices.keys())
predicted_class = class_names[class_index]


display_img = cv2.imread(img_path)
display_img = cv2.cvtColor(display_img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6, 6))
plt.imshow(display_img)
plt.axis('off')

plt.title(
    f"Prediction: {predicted_class}\nConfidence: {confidence:.2f}%",
    fontsize=14
)

plt.show()
